export const BLACK = '#1C252B'
export const BLUE = '#2B365D'
export const DARKGRAY = '#808080'
export const GRAY = '#B2B2B2'
export const LIGHTGRAY = '#E0E0E0'
export const TURQOISE = '#00D7CC'
export const WHITE = '#FEFEFE'
export const WHITESMOKE = '#F0F0F3'
