/* eslint no-undef: 0 */
/* eslint camelcase: 0 */
export default window.Module

const {
  BinauralAPI,
  CCompressor,
  CEarPair_Mono,
  CHearingAidSim,
  CHearingLossSim,
  CListener,
  CMonoBuffer,
  CQuaternion,
  CSingleSourceDSP,
  CStereoBuffer,
  CTransform,
  CVector3,
  EarPairBuffers,
  T_ear,
  TSpatializationMode,
  FloatVector,
  HRIR,
  HRIRVector,
  Logger,
  getLeftEarBuffer,
  ProcessHLS,
  ProcessHAS,
} = window.Module

export {
  BinauralAPI,
  CCompressor,
  CEarPair_Mono,
  CHearingAidSim,
  CHearingLossSim,
  CListener,
  CMonoBuffer,
  CQuaternion,
  CSingleSourceDSP,
  CStereoBuffer,
  CTransform,
  CVector3,
  EarPairBuffers,
  T_ear,
  TSpatializationMode,
  FloatVector,
  HRIR,
  HRIRVector,
  Logger,
  getLeftEarBuffer,
  ProcessHLS,
  ProcessHAS,
}
